import React, { useEffect, useState } from 'react';
import { ShieldCheck, CheckCircle2, AlertCircle, ExternalLink, Terminal } from 'lucide-react';
import { api } from '../lib/api';

export default function BackendStatusBadge({ onOpenDocs }: { onOpenDocs?: () => void }) {
  const [status, setStatus] = useState<'checking' | 'online' | 'offline'>('checking');
  const [details, setDetails] = useState<any>(null);

  useEffect(() => {
    let mounted = true;
    async function check() {
      try {
        const data = await api.checkHealth();
        if (mounted) {
          setStatus('online');
          setDetails(data);
        }
      } catch (err) {
        if (mounted) {
          setStatus('offline');
        }
      }
    }
    check();
    const interval = setInterval(check, 10000);
    return () => {
      mounted = false;
      clearInterval(interval);
    };
  }, []);

  return (
    <div className="flex items-center gap-2">
      <div 
        id="fastapi-health-status"
        title="FastAPI + SQLite Database Connection Status"
        className={`flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold border transition-all ${
          status === 'online'
            ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
            : status === 'checking'
            ? 'bg-amber-50 text-amber-800 border-amber-200'
            : 'bg-rose-50 text-rose-800 border-rose-200'
        }`}
      >
        <span className={`w-2 h-2 rounded-full ${
          status === 'online' ? 'bg-emerald-500 animate-pulse' : status === 'checking' ? 'bg-amber-400' : 'bg-rose-500'
        }`} />
        <span>{status === 'online' ? 'FastAPI + SQLite Online' : status === 'checking' ? 'Connecting...' : 'Offline'}</span>
      </div>

      <a
        id="api-docs-link"
        href="/docs"
        target="_blank"
        rel="noopener noreferrer"
        className="hidden sm:inline-flex items-center gap-1 px-2.5 py-1 text-xs font-medium rounded-full bg-slate-100 hover:bg-slate-200 text-slate-700 transition-colors"
        title="Open interactive Swagger UI docs generated by FastAPI"
      >
        <Terminal className="w-3.5 h-3.5 text-slate-600" />
        <span>Swagger /docs</span>
        <ExternalLink className="w-3 h-3 text-slate-400" />
      </a>
    </div>
  );
}
